/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_alexnet_face_process_FaceProcess */

#ifndef _Included_com_example_alexnet_face_process_FaceProcess
#define _Included_com_example_alexnet_face_process_FaceProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_alexnet_face_process_FaceProcess
 * Method:    initEnv
 * Signature: (Landroid/view/Surface;Landroid/view/Surface;Landroid/view/Surface;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_alexnet_face_process_FaceProcess_initEnv
  (JNIEnv *, jobject, jobject, jobject, jobject);

JNIEXPORT jlong JNICALL Java_com_example_alexnet_face_process_FaceProcess_resetEnv
        (JNIEnv *, jobject, jlong,jobject,jobject,jobject);

/*
 * Class:     com_example_alexnet_face_process_FaceProcess
 * Method:    pause
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_example_alexnet_face_process_FaceProcess_pause
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_alexnet_face_process_FaceProcess
 * Method:    stop
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_example_alexnet_face_process_FaceProcess_stop
  (JNIEnv *, jobject, jlong, jint);

JNIEXPORT jlong JNICALL Java_com_example_alexnet_face_process_FaceProcess_start
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_alexnet_face_process_FaceProcess
 * Method:    detAndShow
 * Signature: (JLandroid/view/Surface;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_alexnet_face_process_FaceProcess_detAndShow
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_example_alexnet_face_process_FaceProcess
 * Method:    detAndCompairAndShow
 * Signature: (J[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_alexnet_face_process_FaceProcess_detAndCompairAndShow
  (JNIEnv *, jobject, jlong, jbyteArray,jint,jint,jint);

#ifdef __cplusplus
}
#endif
#endif
